// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjdvwehniivfqynctqsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZHZ3ZWhuaWl2ZnF5bmN0cXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjgxMDksImV4cCI6MjA3MDEwNDEwOX0.ucqeE2z9zURgIobU3ACp_lOw8ai6whaA9Wp1hb3n0jM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});